const types = {
    CREATE_DECK: "CREATE_DECK",
    LOAD_DECKS: "LOAD_DECKS",
    DELETE_DECK: "DELETE_DECK",

    LOAD_DECK: "LOAD_DECK",
    SET_CURRENT_CARD: "SET_CURRENT_CARD",
    INCREMENT_PROGRESS_INDEX: "INCREMENT_PROGRESS_INDEX",

    
    OPEN_MODAL: "OPEN_MODAL",
    CLOSE_MODAL: "CLOSE_MODAL",

    SET_CARDS_VIEW_ID: "SET_CARDS_VIEW_ID",

    SET_CARD_EDIT: "SET_CARD_EDIT"
};

export default types;