const types = {
    CREATE_DECK: "CREATE_DECK",
    LOAD_DECKS: "LOAD_DECKS",

    LOAD_DECK: "LOAD_DECK",
    SET_CURRENT_CARD: "SET_CURRENT_CARD",
    INCREMENT_PROGRESS_INDEX: "INCREMENT_PROGRESS_INDEX",

    
    OPEN_MODAL: "OPEN_MODAL",
    CLOSE_MODAL: "CLOSE_MODAL"
};

export default types;