const types = {
    CREATE_DECK: "CREATE_DECK",
    LOAD_DECKS: "LOAD_DECKS",
    DELETE_DECK: "DELETE_DECK",
    
    INCREMENT_PRACTICE_COUNT: "INCREMENT_PRACTICE_COUNT",
    RESET_PRACTICE_COUNT: "RESET_PRACTICE_COUNT",    
    SET_TOTAL: "SET_TOTAL",

    OPEN_MODAL: "OPEN_MODAL",
    CLOSE_MODAL: "CLOSE_MODAL",

    SET_CARDS_VIEW_ID: "SET_CARDS_VIEW_ID",

    SET_CARD_EDIT: "SET_CARD_EDIT",

    SET_USER: "SET_USER"
};

export default types;